var fotos = [
   {
      "longitud":"999.99",
      "latitud":"999.99",
      "pais":"Country",
      "lugares":[
         {
            "longitud":"888.88",
            "latitud":"888.88",
            "lugar":"Place",
            "fotos":[
               "picture1.jpg",
               "picture2.jpg"
            ]
         },
         {
            "longitud":"888.88",
            "latitud":"888.88",
            "lugar":"Place",
            "fotos":[
               "picture1.jpg",
               "picture2.jpg"
            ]
         }
      ]
   },
   {
      "longitud":"999.99",
      "latitud":"999.99",
      "pais":"Country",
      "lugares":[
         {
            "longitud":"888.88",
            "latitud":"888.88",
            "lugar":"Place",
            "fotos":[
               "picture1.jpg",
               "picture2.jpg"
            ]
         },
         {
            "longitud":"888.88",
            "latitud":"888.88",
            "lugar":"Place",
            "fotos":[
               "picture1.jpg",
               "picture2.jpg"
            ]
         }
      ]
   }
];